"""One-time re-embed of archival memory onto bge-small-en-v1.5 (384-d).

    python -m memory_server.storage.migrate_embeddings           # default path
    python -m memory_server.storage.migrate_embeddings --path X  # explicit
    python -m memory_server.storage.migrate_embeddings --dry-run

A Chroma collection's vector width is fixed when it is created, so passages
written by the old 512-d hashing embedder cannot coexist with 384-d ones:
queries against a mixed collection fail outright. Chroma already stores the
passage text, so the migration re-embeds from the stored documents — nothing is
regenerated by an LLM and no content is lost.

Idempotent: a collection already at 384-d is left untouched, so re-running is
safe. Back up ``data/`` first regardless (``cp -r data data.bak``).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import chromadb
from chromadb.config import Settings

from . import embedder

COLLECTION = "archival"


def _existing_dim(col) -> int | None:
    """Width of the vectors already stored, or None for an empty collection."""
    got = col.get(include=["embeddings"], limit=1)
    vectors = got.get("embeddings")
    if vectors is None or len(vectors) == 0:
        return None
    return len(vectors[0])


def migrate(path: str, dry_run: bool = False) -> int:
    """Re-embed every passage in ``path``. Returns the number re-embedded."""
    if not Path(path).exists():
        print(f"No archival store at {path!r} — nothing to migrate.")
        return 0

    client = chromadb.PersistentClient(path=path, settings=Settings(anonymized_telemetry=False))
    col = client.get_or_create_collection(
        name=COLLECTION, embedding_function=None, metadata={"hnsw:space": "cosine"}
    )

    total = col.count()
    if total == 0:
        print("Archival store is empty — nothing to migrate.")
        return 0

    dim = _existing_dim(col)
    if dim == embedder.EMBED_DIM:
        print(f"Already {embedder.EMBED_DIM}-d ({total} passages) — nothing to do.")
        return 0

    print(f"Re-embedding {total} passage(s): {dim}-d -> {embedder.EMBED_DIM}-d")
    payload = col.get(include=["documents", "metadatas"])
    ids = list(payload["ids"])
    documents = list(payload["documents"])
    metadatas = [dict(m or {}) for m in payload["metadatas"]]

    if dry_run:
        print("--dry-run: no changes written.")
        for doc in documents[:5]:
            print(f"  would re-embed: {doc[:70]!r}")
        return 0

    vectors = embedder.embed_many(documents)

    # Drop and rebuild: the width is baked into the collection, so it cannot be
    # widened in place. Everything needed is already held in memory above.
    client.delete_collection(COLLECTION)
    fresh = client.get_or_create_collection(
        name=COLLECTION, embedding_function=None, metadata={"hnsw:space": "cosine"}
    )
    fresh.add(ids=ids, embeddings=vectors, documents=documents, metadatas=metadatas)

    print(f"Done — {fresh.count()} passage(s) now at {embedder.EMBED_DIM}-d.")
    return len(ids)


def main(argv: list[str] | None = None) -> int:
    try:
        import config

        default_path = config.CHROMA_PATH
    except Exception:  # pragma: no cover - config import is best-effort
        default_path = str(Path("data") / "chroma")

    ap = argparse.ArgumentParser(prog="migrate_embeddings")
    ap.add_argument("--path", default=default_path, help="Chroma store path")
    ap.add_argument("--dry-run", action="store_true", help="report without writing")
    args = ap.parse_args(argv)

    migrate(args.path, dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
